int f(int a, int b, int c, int d, int e, int f, int g, int h, int i, int j, int k, int l, int m, int n, int o, int p, int q, int r, int s, int t, int u, int v, int w, int x, int y, int z) {
    int sum = 0;
    for(int ii = 0; ii < a; ++ii) sum += 1;
    for(int ii = 0; ii < b; ++ii) sum += 1;
    for(int ii = 0; ii < c; ++ii) sum += 1;
    for(int ii = 0; ii < d; ++ii) sum += 1;
    for(int ii = 0; ii < e; ++ii) sum += 1;
    for(int ii = 0; ii < f; ++ii) sum += 1;
    for(int ii = 0; ii < g; ++ii) sum += 1;
    for(int ii = 0; ii < h; ++ii) sum += 1;
    for(int ii = 0; ii < i; ++ii) sum += 1;
    for(int ii = 0; ii < j; ++ii) sum += 1;
    for(int ii = 0; ii < k; ++ii) sum += 1;
    for(int ii = 0; ii < l; ++ii) sum += 1;
    for(int ii = 0; ii < m; ++ii) sum += 1;
    for(int ii = 0; ii < n; ++ii) sum += 1;
    for(int ii = 0; ii < o; ++ii) sum += 1;
    for(int ii = 0; ii < p; ++ii) sum += 1;
    for(int ii = 0; ii < q; ++ii) sum += 1;
    for(int ii = 0; ii < r; ++ii) sum += 1;
    for(int ii = 0; ii < s; ++ii) sum += 1;
    for(int ii = 0; ii < t; ++ii) sum += 1;
    for(int ii = 0; ii < u; ++ii) sum += 1;
    for(int ii = 0; ii < v; ++ii) sum += 1;
    for(int ii = 0; ii < w; ++ii) sum += 1;
    for(int ii = 0; ii < x; ++ii) sum += 1;
    for(int ii = 0; ii < y; ++ii) sum += 1;
    for(int ii = 0; ii < z; ++ii) sum += 1;
    return sum;
}
